### ISSUE TITLE
New 1.1.0 release is not available through packagist.

### ISSUE THREAD

**Issue by ADmad** [InfinityWebMe/glide-optimizer#6]
"This package is not auto-updated." message is shown below the versions list on https://packagist.org/packages/infinityweb/glide-optimizer

**Comment by YannikFirre** [comment]
@ADmad It's done for this version, i'll look at it to understand why it's not in auto-updated. Thanks =)

**Comment by ADmad** [comment]
> i'll look at it to understand why it's not in auto-updated.

Maybe you need to update the Github URL for the package so that packagist's webhook get's updated, since you moved the repo from `InfinitiyWeb` to under `YanniFirre`.
